/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tiendaropa;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author DRDRA
 */
public class ActVentas extends javax.swing.JFrame {

    /**
     * Creates new form ActVentas
     */
    public ActVentas() {
        initComponents();
        rellenarCombo();
    }

    //Conexion a la base de datos ACCESS tienda de ropa
    private Connection Conexion(){
        //se crea una con objeto conexion
        Connection conex=null;
        
        try {
            //se indica el directorio de la base de datos
            String connectionUrl = "C:\\tareas\\tarea03\\tiendaropa.mdb";
            //Se obtine la conexión
            Connection con=DriverManager.getConnection("jdbc:ucanaccess://"+connectionUrl);
            conex = con;
        } catch (SQLException ex) {
            Logger.getLogger(AppTienda.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        //se comparte la conexion con el resto de la clase.
        return conex;
    }
    
    //rellenar el combobox con el numero de los empleados.
    private void rellenarCombo(){
        try {
            jCVenta.removeAllItems();
            jCVenta.addItem("Seleccione una venta");
            //se obtine la conexion 
            Connection con = this.Conexion();
           
            Statement stmt = con.createStatement();

            //se obtiene el resultado de la consulta
            ResultSet rs = stmt.executeQuery("SELECT * from productos");
 
            // Mientras queden datos
            while (rs.next()) {
                //rellenar el combobox
                String nombre = rs.getString("nombre");
                jCVenta.addItem(nombre);
            }
            
                               
       } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
       }
    }
    
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jCVenta = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTcod = new javax.swing.JTextField();
        jTNombre = new javax.swing.JTextField();
        jTCantidad = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTcodEmp = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel1.setText("ACTUALIZAR VENTAS");

        jCVenta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una venta" }));
        jCVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCVentaActionPerformed(evt);
            }
        });

        jLabel2.setText("Código de venta:");

        jLabel3.setText("Nombre del producto:");

        jLabel4.setText("Código empleado:");

        jLabel5.setText("Cantidad:");

        jTcod.setEnabled(false);

        jLabel6.setText("Unidades");

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/application-exit.png"))); // NOI18N
        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Actualizar venta");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jCVenta, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(36, 36, 36)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jTCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel6)
                                        .addGap(0, 96, Short.MAX_VALUE))
                                    .addComponent(jTcodEmp)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTcod, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTNombre))))
                        .addGap(31, 31, 31))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTcod, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTcodEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //se cierra la ventana cuando se pulse el boton salir
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    //se rellenan los campos al seleccionar un producto de venta
    private void jCVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCVentaActionPerformed
        try {

            //se obtine la conexion 
            Connection con = this.Conexion();
           
            Statement stmt = con.createStatement();

            //se obtiene el resultado de la consulta
            ResultSet rs = stmt.executeQuery("SELECT * from productos WHERE nombre=\'"+jCVenta.getSelectedItem()+"\'");
 
            // Mientras queden datos
            while (rs.next()) {
                //rellenar el combobox
                int cod = rs.getInt("Codigo_producto");
                String nombre = rs.getString("nombre");
                int emp = rs.getInt("codigo_empleado");
                int cantidad = rs.getInt("numero_venta");
                
                jTcod.setText(Integer.toString(cod));
                jTNombre.setText(nombre);
                jTcodEmp.setText(Integer.toString(emp));
                jTCantidad.setText(Integer.toString(cantidad));
                
            }
            
                               
       } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
       }
    }//GEN-LAST:event_jCVentaActionPerformed

    //se actualizara la venta si no hay errores
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            
            //se obtiene los valores de los campos
            String nombre  = jTNombre.getText();
            String empleado = jTcodEmp.getText();
            String cantidad = jTCantidad.getText();
            String cod = jTcod.getText();
            
            //variable de auxiliar para controlar los errores
            int aux =0;
        
            //se comprueba que los campos empleado y cantidad contengan numeros
            Pattern pat = Pattern.compile("\\D");
            Matcher emp = pat.matcher(empleado);
            Matcher can = pat.matcher(cantidad);
        
            //bucle de control de errores
            if(nombre.equals("") || nombre==null){
                JOptionPane.showMessageDialog(null, "El campo nombre del producto no puede estar vacio");
                aux=1;
            }else if(empleado.equals("") || empleado==null){
                JOptionPane.showMessageDialog(null, "El campo empleado no puede estar vacio");
                aux=1;
            }else if(cantidad.equals("") || cantidad==null){
                JOptionPane.showMessageDialog(null, "El campo cantidad no puede estar vacio");
                aux=1;
            }else if(emp.matches()){
                JOptionPane.showMessageDialog(null, "El campo empleado deben ser números");
                aux=1;
            }else if(can.matches()){
                JOptionPane.showMessageDialog(null, "El campo cantidad deben ser números");
                aux=1;
            }
        
            //si hay errores se muestra un mensajes, si no se actualiza el registro de venta
            if(aux!=0){
                JOptionPane.showMessageDialog(null, "Debe rellenar correctamente los campos");
            }else{
                
                Connection con = this.Conexion();
                
                //sentencia preparada para la actualizacion del registro
                String SQL = "UPDATE productos SET nombre=?, codigo_empleado=?, numero_venta=? WHERE Codigo_producto=?"; 
                PreparedStatement sentencia = con.prepareStatement(SQL);
            
                int codemp = Integer.parseInt(empleado);
                int canti = Integer.parseInt(cantidad);
                int codigo = Integer.parseInt(cod);
            
                sentencia.setString(1, nombre);
                sentencia.setInt(2, codemp);
                sentencia.setInt(3, canti);
                sentencia.setInt(4, codigo);
                sentencia.executeUpdate();
            
                JOptionPane.showMessageDialog(null, "Se ha actualizado la venta");
                //rellena el desplegable 
                rellenarCombo();
                //selecciona el el item que sea igual al campo nombre
                jCVenta.setSelectedItem(jTNombre.getText());
            }
                        
        } catch (SQLException ex) {
            Logger.getLogger(ActVentas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jCVenta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTCantidad;
    private javax.swing.JTextField jTNombre;
    private javax.swing.JTextField jTcod;
    private javax.swing.JTextField jTcodEmp;
    // End of variables declaration//GEN-END:variables
}
