/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tiendaropa;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DRDRA
 */
public class LisVenNombre extends javax.swing.JFrame {

    //se crea una tabla
    DefaultTableModel modeloTabla;
    
    /**
     * Creates new form LisVenNombre
     */
    public LisVenNombre() {
        modeloTabla = new DefaultTableModel(null, getColumnas());
        initComponents();
        rellenarCombo();
    }

    //se da formato a la tabla
    private String[] getColumnas(){

        String columna[] = {"Código producto","Nombre del producto","Nombre del empleado","Cantiad de venta"};
        
        return columna;
    }
    
    //Conexion a la base de datos ACCESS tienda de ropa
    private Connection Conexion(){
        //se crea una con objeto conexion
        Connection conex=null;
        
        try {
            //se indica el directorio de la base de datos
            String connectionUrl = "C:\\tareas\\tarea03\\tiendaropa.mdb";
            //Se obtine la conexión
            Connection con=DriverManager.getConnection("jdbc:ucanaccess://"+connectionUrl);
            conex = con;
        } catch (SQLException ex) {
            Logger.getLogger(AppTienda.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        //se comparte la conexion con el resto de la clase.
        return conex;
    }
    
    //rellenar el combobox con el numero de los empleados.
    private void rellenarCombo(){
        try {
            jCVentas.removeAllItems();
            jCVentas.addItem("Seleccione una venta");
            //se obtine la conexion 
            Connection con = this.Conexion();
           
            Statement stmt = con.createStatement();

            //se obtiene el resultado de la consulta
            ResultSet rs = stmt.executeQuery("SELECT * from productos");
 
            // Mientras queden datos
            while (rs.next()) {
                //rellenar el combobox
                String nombre = rs.getString("nombre");
                jCVentas.addItem(nombre);
            }
            
                               
       } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
       }
    }
      
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jCVentas = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel1.setText("LISTA DE VENTA CON NOMBRES DE EMPLEADOS");

        jTable1.setModel(modeloTabla);
        jScrollPane1.setViewportView(jTable1);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/application-exit.png"))); // NOI18N
        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jCVentas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un producto" }));
        jCVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCVentasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 561, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jCVentas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jCVentas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //se cierra la venta al pulsar el boton salir
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    //se muestra los empleados que han vendido un articulo seleccionado en el desplegable
    private void jCVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCVentasActionPerformed
        try {

            //se obtine la conexion 
            Connection con = this.Conexion();
           
            Statement stmt = con.createStatement();

            //se obtiene el resultado de la consulta
            ResultSet rs = stmt.executeQuery("SELECT productos.Codigo_producto as cod, productos.nombre as pro, empleados.nombre as emp, productos.numero_venta as cantidad from productos, empleados WHERE productos.codigo_empleado=empleados.Codigo_empleado AND productos.nombre=\'"+jCVentas.getSelectedItem()+"\'");
            
            // Mientras queden datos
            while (rs.next()) {
                //rellenar el combobox
                Object[] fila = new Object[4];
                
                fila[0] = rs.getLong("cod");
                fila[1] = rs.getString("pro");
                fila[2] = rs.getString("emp");
                fila[3] = rs.getLong("cantidad");
                           
                modeloTabla.addRow(fila);
            }
            
                               
       } catch (SQLException ex) {
           System.out.println(ex);
            JOptionPane.showMessageDialog(null, ex);
       }
    }//GEN-LAST:event_jCVentasActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jCVentas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
