 /* To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tiendaropa;


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author DRDRA
 */
public class VentaReg extends javax.swing.JFrame {

    /**
     * Creates new form VentaReg
     */
    public VentaReg() {
        initComponents();
        rellenarCombo(); 
    }

    //Conexion a la base de datos ACCESS tienda de ropa
    private Connection Conexion(){
        //se crea una con objeto conexion
        Connection conex=null;
        
        try {
            //se indica el directorio de la base de datos
            String connectionUrl = "C:\\tareas\\tarea03\\tiendaropa.mdb";
            //Se obtine la conexión
            Connection con=DriverManager.getConnection("jdbc:ucanaccess://"+connectionUrl);
            conex = con;
        } catch (SQLException ex) {
            Logger.getLogger(AppTienda.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        //se comparte la conexion con el resto de la clase.
        return conex;
    }
    
    //rellenar el combobox con el numero de los empleados.
    private void rellenarCombo(){
        try {

            //se obtine la conexion 
            Connection con = this.Conexion();
           
            Statement stmt = con.createStatement();

            //se obtiene el resultado de la consulta
            ResultSet rs = stmt.executeQuery("SELECT * from empleados");
 
            // Mientras queden datos
            while (rs.next()) {
                //rellenar el combobox
                String cod = Integer.toString((int) rs.getInt("Codigo_empleado"));
                jCEmpleado.addItem(cod);
            }
            
                               
       } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
       }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTNomPro = new javax.swing.JTextField();
        jCEmpleado = new javax.swing.JComboBox<>();
        jTCantidad = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel1.setText("REGISTRO DE VENTAS");

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/application-exit.png"))); // NOI18N
        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Registrar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setText("Nombre del producto:");

        jLabel3.setText("Empleado:");

        jLabel4.setText("Cantidad de venta:");

        jTNomPro.setText("Producto");

        jCEmpleado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un empleado" }));

        jTCantidad.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTCantidad.setText("0");

        jLabel5.setText("Unidades");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCEmpleado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jTCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel5))
                                    .addComponent(jTNomPro, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTNomPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jCEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //al pulsar el boton salir se cierra la ventana
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    //al pulsar el boton de registro se registrara la venta
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        //variable auxiliar para controlar los errores
        int aux=0;
        
        //se obtiene los valores de los campos
        String nombre = jTNomPro.getText();
        String empleado = (String) jCEmpleado.getSelectedItem();
        String cantidad = jTCantidad.getText();
        
        //se comprueba que el campo cantidad contenga un valor numerico
        Pattern pat = Pattern.compile("\\D");
        Matcher mat = pat.matcher(cantidad);
       
        //si el nombre es igual a Producto muenstra un mensaje
        if(nombre.equals("Producto")){
            JOptionPane.showMessageDialog(null, "Debe introducir el nombre del producto");
            aux=1;
        }
        
        //si el campo es igual a 0 o no contiene valores numericos muestra un error
        if(cantidad.equals("0")){
            JOptionPane.showMessageDialog(null, "Debe introducir un valor superior a 0");
            aux=1;
        }else if(mat.matches()){
            JOptionPane.showMessageDialog(null, "Debe introducir un número en el campo cantidad");
            aux=1;
        }

        //si el desplegabel esta seleccionado el index 0 muestra un mensaje
        if(jCEmpleado.getSelectedIndex()==0){
            JOptionPane.showMessageDialog(null, "Debe seleccionar un empleado");
            aux=1;
        }
        
        //si hay errores muestra un mensaje, si no inserta la venta en la tabla
        if(aux==1){
            JOptionPane.showMessageDialog(null, "Compruebe que ha rellenado los campos correctamente");
        }else{
            try{
                Connection con = this.Conexion();
                
                PreparedStatement sentencia;
                sentencia = con.prepareStatement("INSERT INTO productos VALUES (?,?,?,?) ");
                
                int can = Integer.parseInt(cantidad);
                int emp = Integer.parseInt(empleado);
                
                sentencia.setInt(1,0);
                sentencia.setString(2,nombre);
                sentencia.setInt(3, emp);
                sentencia.setInt(4, can);
                
                sentencia.executeUpdate();
              
                JOptionPane.showMessageDialog(null, "Se ha registrado la venta.");
                
            }catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jCEmpleado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTCantidad;
    private javax.swing.JTextField jTNomPro;
    // End of variables declaration//GEN-END:variables
}
